#102 admin tiedotteihin data, myös muissakin tiedotteissa on nyt data
HuHu24/huhu-sovellus pull request #106
Opened 2024-03-22 11:31 UTC by peedudu

2024-03-22 15:33 UTC, Aromiii commented on src/app/admin/releases/[releaseId]/page.tsx
> +  }, [data, releaseId])
Tälläset tupla hyppäykset pois. Sen voi suoraan siihen dataan settaa eikä tarvi tehdä tollasta et eka anyyn ja sit vasta siihen lopulliseen kohteeseen.

2024-03-22 16:33 UTC, Aromiii requested changes
Tosiaan muutamia bugeja ja refactoroivattavaa, että koodin laatu pysyy korkeella. 

Muuten hyvää työtä ja kiitos vaikka tässä kesti. Huhu sovellus on jo tosi pitkällä ja oon erittäin tyytyväinen. 

#### Yleisiä bugeja/asioita/korjattavaa...
- Koodi oli tosi ahdista eli selvempää koodista tekemällä selviä jakoja rivien välissä eikä vain että jokainen rivi koskettaa yllä ja alla olevaa
- datatyypissä ei mitään huuptihuupteja. Noudatetaan edelleenkin figjamia jos ominaisuudet ei vaadi poikkeuksia eli ei eroteltuna aikaa ja päivämäärää vaan datetimen käyttö. Tollanen erittely pitkällä aikavälillä tekee elämästä super ikävää. (figjamissa toki se poikkeus että pienellä kirjaimella kaikki alkaa)

2024-03-22 16:33 UTC, Aromiii commented on src/app/admin/releases/new/page.tsx
>    const divRef = useRef(null)
componentin alkuun kaikki useStatet sekä router

2024-03-22 16:33 UTC, Aromiii commented on src/app/admin/releases/new/page.tsx
> +  }, [formValues])
Pois turha console log

2024-03-22 16:33 UTC, Aromiii commented on src/app/admin/releases/new/page.tsx
>                title="Julkaisu"
Julkaisu -> Julkaistu

2024-03-22 16:33 UTC, Aromiii commented on src/app/admin/releases/new/page.tsx
>                form={"main"}
Sama juttu kun toisessa. Miksi id formilla?

2024-03-22 16:33 UTC, Aromiii commented on src/app/api/releases/route.ts
> +}
Jos kopioidaan koodia niin pliis poistetaan se täysin turha get joka on täysin samanalainen toisessakin endpointissa

2024-03-22 16:33 UTC, Aromiii commented on src/app/api/releases/route.ts
> +  console.log(a)
consolo logit pois

2024-03-22 16:33 UTC, Aromiii commented on src/app/api/releases/route.ts
> +  console.log(data)
Console logit

2024-03-22 16:33 UTC, Aromiii commented on src/app/api/releases/route.ts
Ei tarvi autentikaatiota chekkaa kun middleware hoitaa sen. Lisäksi mikä tän koko routen pointti on, kun eikö voi vain frontendistä suoraan hoitaa noi tiedotteet databasen eikä tarvi tälläsiä hooptihuuppeja tehdä. Turhaa aikaa ja resursseja menee tähän eli koodin refactorointi frontendistä suoraan tiedotteet lähettämään.

2024-03-22 16:33 UTC, Aromiii commented on src/app/auth/signout/route.tsx
> +    new URL(`${process.env.NEXT_PUBLIC_URL}/subcamp`, request.url)
process edestä pois ja käyttämään env varianle env.ts:stä

2024-03-22 16:33 UTC, Aromiii commented on src/firebase.ts
> +    console.log("Document data:", docSnap.data())
Tälläset debug console logit pois

2024-03-22 16:33 UTC, Aromiii commented on src/firebaseAdmin.ts
> +  const snapshot = await releasesRef.get()
Tän vois inlinee. Tulis paljon selvempi

2024-03-22 16:33 UTC, Aromiii commented on src/firebaseAdmin.ts
> +    console.log("Document written with ID: ", docRef.id)
Edelleen tälläset debug consolelogit ei

2024-03-22 16:33 UTC, Aromiii commented on src/components/release/release.tsx
> -  julkaisija: "Minä/osaalue",
Sijoita app/types/.ts tiedostoon intefacet

2024-03-22 16:46 UTC, peedudu commented on src/app/admin/releases/[releaseId]/page.tsx
> +            id={"main"}
koska tein sen joskus ja sit en enään uskaltanut poistaa 👍

2024-03-25 11:41 UTC, peedudu commented on src/app/api/releases/route.ts
> +}
Hups sitä piti käyttää johonkin mut sit sitä ei käytettykkään mihinkään

2024-03-25 18:19 UTC, Aromiii requested changes
Vielä mukana olevia bugeja
- Tiedotteita ei pysty edelleenkään muokkaamaan ja sen uuden tekstin kirjoittaminen ei vain toimi
- Kun on tallentanut tiedotteen, jossa on jotain formatointia esim new lines, niin se ei tallenna sitä vaan murskaa kaiken yhteen mössöön. Se siis korjattava, että formatointi pysyy.

2024-03-25 18:19 UTC, Aromiii commented on src/app/admin/releases/new/page.tsx
> +              title="Julkaitsu"
Kirjoitusasu

2024-03-25 18:19 UTC, Aromiii commented on src/components/adminRelease/menuButton.tsx
>      .replace(".", ":")
Suomessa aika kirjoitetaan pisteellä eikä kaksoispisteellä esim 17.32 eikä 17:32

Tämän voi kyllä tehdä vasta final touches branchissa.

2024-03-25 18:19 UTC, Aromiii commented on src/types/releases.ts
> +export interface releaseData {
Isolla type eli ReleaseData ja musta tässä nimenä vois olla ihan vaan Release jos se ei tuota componenttien kanssa ongelmia

2024-03-25 18:19 UTC, Aromiii commented on src/app/admin/releases/[releaseId]/page.tsx
Edelleen ei pysty muokkaamaan tiedotteita. Kun yrittää kirjoittaa kenttään jotain, niin se ei vaan anna sen kirjoittaa sitä.

2024-03-25 18:19 UTC, Aromiii commented on src/types/releases.ts
Nimi sen sisällä olevan tyypin mukaan eli tässä tilanteessa releaseData

2024-03-25 18:19 UTC, Aromiii commented on src/types/menuButton.ts
sama juttu et filen nimi sisällä olevan typen mukaan

2024-03-25 18:32 UTC, peedudu commented on src/types/releases.ts
> +export interface releaseData {
oletan että se tuottaa niin helpompi näin

2024-03-25 18:50 UTC, Aromiii approved these changes

2024-03-25 18:50 UTC, merged