Sovellusmatskut #118
HuHu24/huhu-sovellus pull request #152
Opened 2024-04-24 16:07 UTC by Aromiii

2024-04-25 14:01 UTC, peedudu requested changes

2024-04-27 09:40 UTC, Aromiii commented on src/app/info/page.tsx
Tää jäi niinku haamusivuks vahingossa eli tätä ei ole edes tulossa

2024-04-27 09:41 UTC, Aromiii commented on src/app/info/subcamp/page.tsx
Mietin sitä samaa et onkohan ne external linkit ongelmat. Selvitän sen ylempää, että miten toimitaan

2024-04-27 14:07 UTC, peedudu approved these changes

2024-04-27 15:26 UTC, merged